### ISSUE TITLE
Lottie restores state when lottie view is dynamically added to layout

### ISSUE THREAD

**Issue by adityaarora1** [airbnb/lottie-android#1007]
I am trying to add/remove lottieAnimationView in a frame layout. However, lottie restores to last set frame after a remove/add. I need to reinitialise lottie on adding back.

**Comment by gpeal** [comment]
@adityaarora1 This is the expected behvaior because Lottie can't distinguish between you adding/removing your view or it getting attached/detached in a scenario like a RecyclerView. Adding this functionality would likely break lots of other use cases. Can you just manually reset the view as you have been? You could also write your own wrapper around LottieAnimationView that does it automatically.
