### ISSUE TITLE
Add support for merge paths

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#101]

**Comment by gpeal** [comment]
Merge paths are disabled by default but can be enabled with `enableMergePathsForKitKatAndAbove`.

**Comment by SwayChen** [comment]
Hi, I meet this issue now. 
```
08-16 16:36:28.643 8381-8381/free.vpn.unblock.proxy.vpnmonster W/LOTTIE: Animation contains merge paths but they are disabled.
```

I have set `enableMergePathsForKitKatAndAbove` in XML & Code.
```
<com.airbnb.lottie.LottieAnimationView
    android:id="@+id/anim_view_vpn_status"
    android:layout_width="@dimen/lottie_view_width"
    android:layout_height="wrap_content"
    android:layout_gravity="center_horizontal"
    android:layout_marginTop="@dimen/status_view_top_margin"
    app:lottie_autoPlay="true"
    app:lottie_enableMergePathsForKitKatAndAbove="true"
    app:lottie_loop="true" />
```

```
vpnStatusAnimView = (LottieAnimationView) findViewById(R.id.anim_view_vpn_status);
vpnStatusAnimView.enableMergePathsForKitKatAndAbove(true);
```

**Comment by coryarmbrecht** [comment]
Hey @gpeal @SwayChen , I have run into this issue, but after seeing this thread and doing more digging, I still don't see where / how to properly do this. I tried @SwayChen 's way: `Animation.enableMergePathsForKitKatAndAbove(true)` with no luck, but I don't know where that initial code block goes.

I also tried adding `enableMergePathsForKitKatAndAbove` and `enableMergePathsForKitKatAndAbove={true}` as props to <Animation />

Any help would be appreciated. Thanks!

**Comment by gpeal** [comment]
@coryarmbrecht This prop hasn't been added to lottie-react-native. Feel free to submit a PR or open an issue and I'll do it later.

**Comment by coryarmbrecht** [comment]
@gpeal , thanks, and I'd love to, but a couple things:
1. I don't know java :/ (But, I'm peeking around)
2. Didn't @SwayChen post a solution used? I just don't know what XML file and proper code usage.
3. When you said:

> Merge paths are disabled by default but can be enabled with enableMergePathsForKitKatAndAbove
, did you mean that's how it can be fixed by writing that in the future? That sentence sounds like a feature I can just enable with setting to `true` somewhere. (Wishful thinking ;p )


[Changelog 200-beta 3](https://github.com/airbnb/lottie-android/blob/9f8e004421437fdd7f43a226b2d2745e5b3e312d/CHANGELOG.md#200-beta3) states :
> Some merge path support. Enable it with enableMergePathsForKitKatAndAbove and read the documentation before using it.

In [LottieDrawable.java](https://github.com/airbnb/lottie-android/blob/1d0d8f164caed6699d985193503434f703c65c24/lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java#L98) it appears that you might be able to enable it somehow. I also see the error log at [MergePaths.java](https://github.com/airbnb/lottie-android/blob/2df1c2bac1cb886dce38d64e0b3a80d603e8dc51/lottie/src/main/java/com/airbnb/lottie/model/content/MergePaths.java#L59)

Thanks!

**Comment by gpeal** [comment]
@coryarmbrecht The functionality is there but lottie-react-native doesn't have a prop to enable it yet. I should add it though :)

**Comment by coryarmbrecht** [comment]
Since I can't add with code, can a bounty[source] help this issue? Never done it before, but if would help aid this issue, I'd love to add to it. (I'll probably do this later tonight)

**Comment by coryarmbrecht** [comment]
So Bountysource won't let me throw funds toward a specific commit, but it will allow me to contribute directly to Airbnb. I'm not sure of protocol with things like this or Gratipay, but I'm all ears in anyway I can help this issue.

**Comment by gpeal** [comment]
@coryarmbrecht don't worry about a bounty :)
This repo is Android specific though. Can you file an issue on lottie-react-native?
