### ISSUE TITLE
io stream close is incorrect

### ISSUE THREAD

**Issue by Stonekity** [airbnb/lottie-android#1021]
![issue](https://user-images.githubusercontent.com/3970392/49575739-65910b00-f97e-11e8-9978-0c20375072be.png)

decorate stream should close the outside stream, but not only inside stream ?
in the screenshot above, we should call JsonReader.close(), not InputStream.close()

**Comment by gusthavosouza** [comment]
I think it's not incorrect.
Remember the principal InputStream is ALWAYS the same independently what's the inner class they are used for, because they share the same reference. So this principal InputStream we need ensure that resource is closed on this inner finally or on your method call.
I think this code can be replaced by a call to try-with-resources to close JsonReader and InputStreamReader but if we do that you will close your principal InputStream and maybe get some problems if you dont want it be closed.
Inside the JsonReader close() method they just set free some resources maybe GC will do the work after the execution of fromJsonInputStreamSync().

**Comment by gpeal** [comment]
@Stonekity @gusthavosouza Looking through the code, the only one that seems important to close is the original io stream. The others just null out values/set the state in such a way that they can't be used again.

I can't use try with resources since it was added in KitKat.

Do either of you think that further action is needed here?

**Comment by gusthavosouza** [comment]
@gpeal like I said the only one we need ensure to be closed is the original(principal) io stream.
I was thinking about that try with resources was added in android KitKat :)
I think is not necessary, maybe my answer was a little confused.
Let's wait Stonekity answer.
Thanks :_)

**Comment by gpeal** [comment]
@Stonekity

**Comment by gpeal** [comment]
Going to close this unless otherwise noted.
