### ISSUE TITLE
Can't get lottie animation to play programmatically - fine in XML

### ISSUE THREAD

**Issue by ntohill95** [airbnb/lottie-android#1076]
Hi,

I have added a lottie animation to a fragment. If i set app:lottie_autoPlay="true" in XML then the animation works. However, if I try to start it programmatically in Kotlin in my fragment class it does not play.

XML : 
        <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/lottie_film_animation"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_constraintTop_toBottomOf="@id/linearLayout"
            app:layout_constraintBottom_toTopOf="@id/textView"
            app:lottie_loop="true"
            app:lottie_autoPlay="false"
            app:lottie_fileName="movie.json" />

fragment:

var lottieAnimationView: LottieAnimationView = rootView.findViewById(R.id.lottie_film_animation)
lottieAnimationView.playAnimation()

Gradle:
 implementation 'com.airbnb.android:lottie:2.7.0'

Any suggestions would be appreciated! Thanks for your time

**Comment by gpeal** [comment]
@ntohill95 Can you attach a sample project that repros this?

**Comment by MONIKA-KUMAR-JETHANI** [comment]
Hi @ntohill95 , Is the issue still occurring?

**Comment by Duna** [comment]
When using viewpager2 + fragmentactivity+ androidx the animation is not starting

**Comment by chrislworkaccount** [comment]
Ever find a solution for this?

**Comment by bknmjolner** [comment]
I also experienced this problem.
@Duna Thanks, for mentioning viewpager2 - my case was also with that component, and it made me test with different settings for offscreenPageLimit. 
I have five pages each with one LottieAnimationView. All animations was started except the second one. When I changed offscreenPageLimit to 2 - all was started fine except the fourth one, which is the one right after the preloaded pages, and this compares to the initial case, since the default offscreenPageLimit value is 0. So a solution for me was to set offscreenPageLimit to 4 - even though it would be better not to preload so many pages (but I make sure to pause the animations that are not visible)
