### ISSUE TITLE
Add support for trim path,track mattes

### ISSUE THREAD

**Issue by xuwab** [airbnb/lottie-android#120]
Hello，
   **   I have some problems with using the library.

Here is my ae and json file**
[https://github.com/xuwab/lottiefile/archive/master.zip](url)

There are two ae and json  files, gifs and screenshots. The first ae called "mloading" using trim path and track mattes,but the lines are thicker and the annimations in device are so differrent.
The second ae file use adjusting the opacity and scaling but the annimation is also different in device and the part inside is filled.

**Comment by gpeal** [comment]
@xuwab you have the stroke width set to 1 which is 1dp on Android which is tiny. There is going to be some anti aliasing done by the platform so what you're left with is something extremely thin.
I think what I'm seeing as far as stroke width is concerned is actually correct on the device but you may see slight differences due to platform aliasing.


For the second one, merge paths aren't supported yet but it's on our roadmap.
You can try just setting the stroke on a shape instead. Fyi, polygons will be supported soon as well.

#101
