### ISSUE TITLE
Unnecessary memory allocations in NumberKeyframeAnimation

### ISSUE THREAD

**Issue by 0legg** [airbnb/lottie-android#122]
Issue: If you take a look at memory consumption during the animation (in AS Memory Monitor for example), then you can mention that memory consumption is increased during the animation. I traced memory allocations, and it happened that ≈99% of allocations happens under the hood of `NumberKeyframeAnimation` class. So, as it's generic and parametrized with `Number` (either `Integer` or `Float`), there are lot of unnecessary boxings/unboxings and memory allocations in the heap.

Impact: more memory consumed by animation, bigger amount of garbage collections, worse performance.

Proposed solution: replace `NumberKeyframeAnimation` with specific implementations (`IntKeyframeAnimation`, `FloatKeyframeAnimation`, etc.) manipulating primitive types instead of objects.

**Comment by 0legg** [comment]
If you have no enough time to put your hands on it, I can make a pool request soon =)

**Comment by gpeal** [comment]
@0legg good catch. I was concerned with this when I wrote it but haven't had the chance to do actual profiling yet. I'll definitely look in to this.

**Comment by gpeal** [comment]
@0legg I tagged your other issue by accident but I made some improvements here: https://github.com/airbnb/lottie-android/commit/c10f32690c4bee313829c4db4b08d0a848c38143

I think I could go even further by special casing integer and float to be able to return primitives instead of their wrapped versions too but I was able to knock this out quickly and verify some significant improvements with the memory profiler.

**Comment by gpeal** [comment]
I think I'm going to close this for now. I got rid of some of the bad unboxing and iterator creation offenders. Doing more than this will require totally breaking the generic signature but it is definitely better now than it was.
