### ISSUE TITLE
Lottie Animation has lag when new Activity starts

### ISSUE THREAD

**Issue by z85510** [airbnb/lottie-android#1312]
When I try to start new activity Lottie animation occurs lagging.
I try some dummy solution but it didn't works

`myView.setLayerType(View.LAYER_TYPE_HARDWARE, null)`

`android:hardwareAccelerated="true"`

**Comment by gpeal** [comment]
There are some performance tips [here](http://airbnb.io/lottie/#/android?id=performance).

You want `setRenderMode`, not the native Android APIs.

**Comment by hardikm9850** [comment]
@gpeal I am facing the same issue. 
The animation gets stuck when a new activity is being launched
We tried to do app profiling but that didn't help identifying where exactly the issue is. 

As you mentioned above `setRenderMode ` it is part of GLSurface view and am not sure how that would help with the `lottieview`.
Can you guide me in that respect? Any tool to debug the view performance?

**Comment by gpeal** [comment]
@hardikm9850 It's also a Lottie API
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L918

**Comment by chitgoks** [comment]
This did not help. it seems when a new activity is started, the lottie animation in the old activity stops.

what i wish to achieve is the animation keep on playing until the activity is not visible anymore.

**Comment by DmytroTols** [comment]
Issue still exist in version 4.2.2,when starting new activity Lottie freezes and then start playing again when transition from activities happens,is there a way to make animation keep playing?
