### ISSUE TITLE
Recyclerview, animating when detached

### ISSUE THREAD

**Issue by venjirai** [airbnb/lottie-android#1322]
Version: 3.0.7

I'm using a lottie imageView in an item for a recyclerview.
It is used for a subscribe animation. A user can click on an item and a subscribe animation is playing, when the animation is finished it stays in that position (progress 1.0) to show the changed status.

When the view is binded, I call the following to only show the status but not playing the animation again:

            lav.pauseAnimation();
            if (isSubscribed)
                lav.setProgress(1f);
            else
                lav.setProgress(0f);

The problem occurs, when the view is detached while animating and then comes into the view again without being rebind by the recyclerview (if the user only scrolls a little bit)

Therefore my pauseAnimation() is not called and

  @Override protected void onAttachedToWindow() {
    super.onAttachedToWindow();
    if (autoPlay || wasAnimatingWhenDetached) {
      playAnimation();

will just play the animation again.

If the user scrolls down after playing the animation I want the animation to be in the finished state and not be playing again.
This should also work in reverse, where I set the speed to -1.

How can I achieve this with your library without having to override the adapters 

    public void onViewAttachedToWindow(@NonNull RecyclerView.ViewHolder holder)

and manually pause and set the animation there?

**Comment by YuriiTsap** [comment]
We've faced two really similar issues. I've described mine [here](https://github.com/airbnb/lottie-android/issues/1324). Our two tickets could be coupled I guess. Please have a look at mine description and explanation, maybe that will give you ideas how to fix that. Or you can adjust mine explanation. Thanks.

**Comment by headsvk** [comment]
I have a similar issue where I want to play an animation when an item inside a `RecyclerView` is clicked. 

Hiding some text and showing the animation causes the item to be re-measured and `RecyclerView` detaches itself from the view temporarily without onDetachedFromWindow being called. The animation is not played at this point even if I call `LottieAnimationView.playAnimation()` because `isShown()` returns false (top parent is null). Afterwards the `RecyclerView` attaches itself back again without `onAttachedToWindow()` being called, so the animation is never played.

**Comment by gpeal** [comment]
@headsvk @venjirai  I'm going to merge this into #1324 but my comment on that issue applies to all of you too.
