### ISSUE TITLE
ANR with match_parent in some lotties

### ISSUE THREAD

**Issue by manthesepeasrock** [airbnb/lottie-android#1339]
On at least on a Samsung s8 plus with Android 7 some bigger lotties are crashing the application during the animation, this happens for LottieAnimationView with the layout_width of the view as match_parent or 0dp using constraintStart_toStart and constraintEnd_toEndOf parent and a fixed layout_height

We tried with all 3.0.+ versions of the lib and the same issue happens

In our case to reproduce this issue its only need to open the app and even before the first loop ends the app crashes. Sample project attached [lottie_anr.zip](https://github.com/airbnb/lottie-android/files/3456117/lottie_anr.zip) and the traces.txt from the crash [traces.txt](https://github.com/airbnb/lottie-android/files/3456145/traces.txt)

**Comment by gpeal** [comment]
This is unlikely to be a Lottie specific issue and more likely something else that was slowing down the device to the point where it happened to ANR here.

**Comment by manthesepeasrock** [comment]
I don't know that this is a lottie specific issue, because it works on other devices, and on this device it works if we give it a fixed height and width, only with a match_parent width or height does it crash

**Comment by kakai248** [comment]
@gpeal I did some more tests. It happens on that lottie with exactly 100dp of height and on frame 46. So it's not related with match_parent as originally said.

If the height is 99dp or 101dp it will no longer crash. And that frame is the only one with the issue. If I don't play the animation at all and just set frame = 46, it will crash.

If I set software in render mode it doesn't crash anymore. It also happens on the lottie preview app that is on the store.

Enabling software mode for every device because of a specific crash on one seems like a bad solution. But I'm also not sure which heuristic should I use to enable software only in some particular devices.

**Comment by gpeal** [comment]
@kakai248 Thank you for the specifics!

**Comment by gpeal** [comment]
@kakai248 I just ran your project as well as the same animation within the Lottie repo on a Galaxy S8 running Pie. Most S8's should have Pie by now so maybe it was resolved by Samsung. Can you try again and close this out if possible? If not, if you could take a look using the issue-repro module in the repo and put up a PR, that would be great but I won't be able to unless I can repro it.
