### ISSUE TITLE
Add a null check around getCallback()

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#135]

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/commit/1927fc4d20cb68128bdc069e0ddf4336f23a2ac2

**Comment by jeliza1215** [comment]
Come on big girl trying to play a woman's game
Im about to be on my way to your folks house with the proof I have to let
your daddy know what his lil girl has been up to
If I don't hear from you in 15 mins, I'll be on my way
I do know where you stay or your folks any way




On Feb 20, 2017 2:56 PM, "Gabriel Peal" <notifications@github.com> wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/airbnb/lottie-android/issues/135>, or mute the thread

**Comment by jeliza1215** [comment]
Don't make me do this
I really really don't blame you
I just need some answers
Deja told you to block me OK block me lil lady and you will see me over
there with my proof in front of your family



On Feb 20, 2017 2:56 PM, "Gabriel Peal" <notifications@github.com> wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/airbnb/lottie-android/issues/135>, or mute the thread

**Comment by jeliza1215** [comment]
OK let me see you block Julio
