### ISSUE TITLE
LottieDrawable not displaying correctly on a MaterialButton

### ISSUE THREAD

**Issue by leinardi** [airbnb/lottie-android#1531]
**Describe the bug**
When using a `LottieDrawable` on a `MaterialButton`'s icon the `LottieDrawable` is shown on the wrong position.

![image](https://user-images.githubusercontent.com/273338/76151026-862f9f80-60b0-11ea-8e5e-7a4f5a683d95.png)

The expected position of the icon is the following:
![image](https://user-images.githubusercontent.com/273338/76151042-abbca900-60b0-11ea-9a94-397422bfe7f6.png)

**Steps To Reproduce**

1. Cherry-pick https://github.com/leinardi/lottie-android/commit/ddac7cb033548369ebcec7b435e80af874e02fb7
2. Run the issue-repro app
3. Check the button in the middle of the screen
4. (if there is no animation at all, try to press the button)

**Comment by gpeal** [comment]
I figured out the issue here. MaterialButton assumes that its icon drawable's intrinsic size never changes. However, in your code, you set the drawable on the button before it's composition is set so it returns the default intrinsic width/height of -1.

To work around this, just set the icon on the button after the composition is loaded and it will work just fine.

**Comment by leinardi** [comment]
Hi @gpeal, could we keep this issue open until it is properly fixed?

Also, could you give more details on how to implement the workaround?

**Comment by gpeal** [comment]
@leinardi The bug isn't on the Lottie side, it's on MaterialButton. I looked through the source code for it and there is no way for Lottie to notify the button that its intrinsic size has changed.

To implement the workaround, move
`findViewById<MaterialButton>(R.id.button).icon = lottieDrawable` to the end of the `LottieCompositionFactory` callback (line 21)
