### ISSUE TITLE
Feature request: extend ImageAssetDelegate API to make it possible to provide an animated image (as an AnimationDrawable)

### ISSUE THREAD

**Issue by magicgoose** [airbnb/lottie-android#1581]
**Is your feature request related to a problem? Please describe.**
Currently it's impossible to embed animated images into Lottie animations, because `ImageAssetDelegate` can only provide a `Bitmap`.

**Describe the solution you'd like**
Extend API to let `ImageAssetDelegate` (or similar) provide an arbitrary Drawable classes, including AnimationDrawable

**Describe alternatives you've considered**
I don't think there are any...

**Additional context**
I'm trying to dynamically embed an animated image (formats such as APNG & GIF) between layers of a Lottie animation and realized the current API can't possibly support that.

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by ayshiff** [comment]
I would love to help implementing this new feature!

**Comment by gpeal** [comment]
@magicgoose @ayshiff This might be tricky to implement because Lottie wouldn't really know when to re-render.
However, what you could do here is create an image layer in your animation, then create a bitmap in code, render to it, and return it from a dynamic property for that image layer.

Doing that would actually be pretty efficient and would pretty much match Lottie's software rendering algorithm anyway. Rendering to and drawing bitmaps is very fast on Android. Would this work for you? I'd prefer to keep this solution via existing APIs vs adding new ones.

**Comment by gpeal** [comment]
I'm going to close this for now as I don't see a clean way of integrating this. Feel free to reopen this with a concrete proposal.
