### ISSUE TITLE
Animations appear blurry on pre-pie devices.

### ISSUE THREAD

**Issue by maternalcarestartup** [airbnb/lottie-android#1631]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
On pre API 28 devices, the same animation appears blurry. However, on API 28 and above it seems to work fine. Setting the render mode to software does load the animation without blurring on all devices. Does that mean we shouldn't be rendering Automatic or Hardware render modes yet?

**What version of Lottie did you test this on?**
lottie:3.4.1
**What version of Android did you test this on?**
27 and below
**Steps To Reproduce**
Load animation from https://raw.githubusercontent.com/thesvbd/Lottie-examples/master/assets/animations/skip-forward.json on a pre-28 API android device or emulator.

**Screenshots**

**Comment by gpeal** [comment]
@maternalcarestartup pre-pie, Android used hwui instead of skia. On hardware accelerated hwui canvases, scaling a hardware accelerated canvas was done after rasterizing which means that if you scale it up a lot, it will be pixelated.
You can read about it [here](https://developer.android.com/guide/topics/graphics/hardware-accel#scaling). Unfortunately, there is nothing that Lottie can do about that.
