### ISSUE TITLE
Significant rendering performance issue in v1.5.x as compared to v1.0.x

### ISSUE THREAD

**Issue by asc42** [airbnb/lottie-android#165]
I created a basic animation in AfterEffects involving masks and size changes.

While using Lottie `v1.0.x`, the animated view was the same size as the original composition (512px * 512px), and it used to play smoothly.

However, after updating the library to `v1.5.1`, the view is rendered with larger dimensions (looked like 2x) and there were noticeable lags.

I've reverted to using `v1.0.3`, but I'd like to know why is there such a big performance impact. 
If needed, I can mail the `json` file

**Comment by gpeal** [comment]
@asc42 performance should have improved. Can you send me your after effects file at lottie@airbnb.com and I'll take a look. Having the after effects file instead of the json will make debugging significantly easier. Also, what device did you notice the issue on?

**Comment by asc42** [comment]
@gpeal
I have mailed the AfterEffects file, along with the `json` file.

Device: Nexus 5
OS: [Santosh M's unofficial Nougat build](https://forum.xda-developers.com/google-nexus-5/orig-development/wip-aosp-nougat-nexus-5-t3446875) (7.1.1_r22)

**Comment by gpeal** [comment]
@asc42 I'm almost positive this is due to the large composition size and the removal of the MAX_SIZE restriction here: https://github.com/airbnb/lottie-android/commit/55cc8e3ba3c6acd42f0316d412ed528790c5f600

Your composition will render the dp equivalent of what you have the px size set to in AE so try making your composition smaller.
