### ISSUE TITLE
Caused by: java.lang.ClassCastException: int[] cannot be cast to java.lang.String[]

### ISSUE THREAD

**Issue by jiaopan** [airbnb/lottie-android#1655]
When lottie upgrade to 3.4.2, there are some crash only on Android 4.4.4:

Caused by: java.lang.ClassCastException: int[] cannot be cast to java.lang.String[]
at com.airbnb.lottie.parser.moshi.JsonReader$Options.of(Proguard:388)
at com.airbnb.lottie.parser.LottieCompositionMoshiParser.<clinit>(Proguard:27)
... 19 more

**Comment by gpeal** [comment]
@jiaopan Please attach your animation. There is no way to debug it without that.

**Comment by gpeal** [comment]
I'm going to close this due to inactivity. Please reopen with your animation if you are still having this issue.

**Comment by luohong** [comment]
1 java.lang.IllegalStateException:Unable to parse composition
--
2 com.airbnb.lottie.LottieAnimationView$a.onResult(LottieAnimationView.java:4)
3 ......
4 Caused by:
5 java.lang.ClassCastException:int[] cannot be cast to java.lang.String[]
6 com.airbnb.lottie.parser.moshi.JsonReader$a.of(JsonReader.java:7)
7 com.airbnb.lottie.s.t.<clinit>(LottieCompositionMoshiParser.java:1)
8 com.airbnb.lottie.e.fromJsonReaderSyncInternal(LottieCompositionFactory.java:1)
9 com.airbnb.lottie.e.fromJsonReaderSync(LottieCompositionFactory.java:1)
10 com.airbnb.lottie.e.fromJsonInputStreamSync(LottieCompositionFactory.java:2)
11 com.airbnb.lottie.e.fromJsonInputStreamSync(LottieCompositionFactory.java:1)
12 com.airbnb.lottie.e.fromAssetSync(LottieCompositionFactory.java:4)
13 com.airbnb.lottie.e$d.call(LottieCompositionFactory.java:2)
14 com.airbnb.lottie.e$d.call(LottieCompositionFactory.java:1)
15 java.util.concurrent.FutureTask.run(FutureTask.java:237)
16 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
17 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
18 java.lang.Thread.run(Thread.java:841)
