### ISSUE TITLE
The LottieAnimationView cass full screen update

### ISSUE THREAD

**Issue by MrsLEO** [airbnb/lottie-android#1686]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1.The LottieAnimationView will cause the entire screen to refresh, even if we accurately control the ImageView size

**Describe the bug**

version 3.4.1

Android 11

**Steps To Reproduce**

1. open system setting open show view updates
2. Fix any lottie's LottieAnimationView in the demo code, for example, the width and height are 100dp
3. The entire screen flickers and draws appear

**Screenshots**

**Comment by gpeal** [comment]
@MrsLEO Whenever an Android view is invalidated, the entire screen has to be redrawn for a number of reasons including that views can overlap so to get the fully composited image, you have to render everything.

Under the hood, LottieAnimationView is calling `invalidateDrawable(lottieDrawable)` ([here](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L241)).

If there is a specific performance optimization that you would like to see, I'm open to PRs or specific suggestions. I'm going to close this for now though because it likely isn't actionable.
