### ISSUE TITLE
Support scale bitmap in low resolution devices

### ISSUE THREAD

**Issue by zhangzhige** [airbnb/lottie-android#1705]
Hi，In my app，have some oom crash in low resolution devices，because ours lottie file is design by 1920*1080，but the old devices is 720p or less，I found ImageAssetManager decode the bitmap in the design size，so this is Memory waste，so I hope you can support create scale Bitmap in Lottie-Android。Like this change：
![image](https://user-images.githubusercontent.com/5879656/103128295-b98afb80-46cf-11eb-82c9-740ba8a20b5f.png)
![image](https://user-images.githubusercontent.com/5879656/103128304-c1e33680-46cf-11eb-850b-90121df7e575.png)
![image](https://user-images.githubusercontent.com/5879656/103128311-c871ae00-46cf-11eb-843e-55402aa00b64.png)

if use this code，I can set ImageDelegate to Decode the Small Bitmap，or use native bitmap on below android 8.0 devices

**Comment by zhangzhige** [comment]
when I used the scale bitmap in 720p devices（opts.inSampleSize = 2）, the memory contrast like this
![image](https://user-images.githubusercontent.com/5879656/103128628-00c5bc00-46d1-11eb-99bd-64877d0b1f1f.png)
![image](https://user-images.githubusercontent.com/5879656/103128633-03c0ac80-46d1-11eb-9a5a-981941d4a8d5.png)

**Comment by gpeal** [comment]
@zhangzhige Are you using a BitmapAssetDelegate to return the images at runtime? From my tests, the bitmaps that bodymovin exports are the same size as the image asset metadata in which case, this change has no effect.

**Comment by zhangzhige** [comment]
@gpeal In my case, when ours lottie design by 1920*1080, in 720P devices I can use BitmapAssetDelegate decode     opts.inSampleSize *= 2; to create a small bitmap. It can work well. otherwise, In Lottie, I suggest you can set a param designDensity it mean  lottie design size, such as if lottie is 1920*1080, the designDensity will set 3 by outside. then in ImageAssetManager
![image](https://user-images.githubusercontent.com/5879656/103201165-331e2600-492a-11eb-9280-d3b5c77d0574.png)
![image](https://user-images.githubusercontent.com/5879656/103201173-39ac9d80-492a-11eb-85d0-39055536341c.png)

then It will work simple

**Comment by zhangzhige** [comment]
@gpeal dont scale bigger in Util。
![image](https://user-images.githubusercontent.com/5879656/103201287-81cbc000-492a-11eb-8973-413759a15041.png)

**Comment by gpeal** [comment]
For the first suggestion, the density change, the challenge is that we don't actually know what size the animation will be rendered at. If the composition is 1080p but the phone is 720p, it might be rendered with a scale > 1 such that the full original bitmap resolution is required to render the bimap at its desired quality level.

The challenge with the second one, not scaling the bitmap up, matters because in 4.0, there will be an option to choose between rendering the original bitmap size and always rendering at the design size and the choice can be made at runtime so correct design size bitmap must be retained.

If, for your specific app, this is a concern, I would suggest using dynamic properties with the new 4.0 resizeBitmaps API (requested in [this issue](https://github.com/airbnb/lottie-android/issues/1968)) such that you can provide smaller bitmaps manually if desired.
