### ISSUE TITLE
playAnimation() does nothing on 2nd call in Android

### ISSUE THREAD

**Issue by reedt100** [airbnb/lottie-android#174]
Bug in 1.5.2 Android

Steps to reproduce:
1. Set animation passing String JSON filename
2. Add animation listener that calls playAnimation () in on-end listener method
3. Call playAnimation ()

Observe that animation plays, listener method is called but animation does not play again.

I actually want to alternate between two animations with the listener setting and starting one, then setting and starting another and this isn't working but the above appears to be at the heart of the issue.

I need to use a listener as I need to make other UI changes in sync with the transition between plays.

**Comment by gpeal** [comment]
@reedt100 This will be fixed in 1.5.3. What was happening is that playAnimation behaved like resumeAnimation which set the progress to 1 when you tried to play your new animation. playAnimation will not not change the start progress whereas resumeAnimation will behave like playAnimation used to. I'll release it in the next few days.

**Comment by reedt100** [comment]
Thanks, I appreciate it. I tried setting progress to 0 before calling play the 2nd time but that didn't appear to help so I look forward to your fix.

**Comment by ArihantJain456** [comment]
I am also facing the same problem

**Comment by nikulcears** [comment]
why this issue has been closed. still there is no solution to play animation **2nd time**

**Comment by ganeshpadhayay** [comment]
I am also facing this issue, please mark it open and look into it
