### ISSUE TITLE
Failed to sync project

### ISSUE THREAD

**Issue by Luosoha** [airbnb/lottie-android#1754]
Build file 'D:\********\lottie-android\issue-repro\build.gradle' line: 1

A problem occurred evaluating project ':issue-repro'.
> Failed to apply plugin 'com.android.internal.application'.
   > java.lang.NoSuchMethodException: java.lang.invoke.MethodHandles.privateLookupIn(java.lang.Class, java.lang.invoke.MethodHandles$Lookup)

I cloned the project and can't even sync and build it, I think it has something to do with this
**classpath 'com.android.tools.build:gradle:7.0.0-alpha08'**
and the **gradle-wrapper.properties's distributionUrl**

I'm using Android Studio 4.1.2. Any help would be much appreciated, thanks!

**Comment by jossiwolf** [comment]
Lottie-Android depends on the latest AGP and Android version in order to enable Compose-related features (see https://github.com/airbnb/lottie-android#contributing).

Please make sure that
- You are using the latest Android Studio Canary (Android Studio Arctic Fox Alpha 08 currently)
- You are using JDK 11 (https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html)

Builds should work with that setup.

**Comment by gpeal** [comment]
@Luosoha, @jossiwolf is correct, to support Compose, you must use the Arctic Fox canary with Lottie.
