### ISSUE TITLE
Compose Desktop

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [airbnb/lottie-android#1800]
I haven't checked all the files but I would like to ask a few things:

- Is it planned to add support to compose desktop? As a JVM artifact.

- I checked there is a few java dependencies that maybe can be replaced with Okio some day. Creating the compose artifact as Multiplatform can be an option in the future?

**Comment by gpeal** [comment]
@JavierSegoviaCordoba There are no plans without a significant rewrite. Lottie Compose currently wraps the existing Android Drawable which heavily depends on the Android SDK.

I've spent a significant amount of time thinking about how to build a fully Compose renderer and there isn't a trivial solution with out a ground up rewrite and potentially new performance problems.

It would be great to see this one day but it's not as trivial as removing okio and I'm going to close this for now since it's a ground up rewrite that may or may not happen.

**Comment by JavierSegoviaCordoba** [comment]
Thank you for your reply :)
