### ISSUE TITLE
the onDestroy() of pervious activity is called delay

### ISSUE THREAD

**Issue by YangX29** [airbnb/lottie-android#1910]
I have 2 activities in my project. And the Activity A has two `LottieAnimationView` that automatically loop(`app:lottie_loop="true"` and `app:lottie_autoPlay="true"`). When I start Activity B from Activity A and then finish it, the `onDestroy` method of ActivityB is called delayed.

After testing, I guessed that this was caused by the existence of multiple LottieAnimationViews that automatically looped in Activity A. If I close one of them by setting `app:lottie_autoPlay="false"`, the bug will be solved.

I have checked the Issue [#641](https://github.com/airbnb/lottie-android/issues/641), but turning off hardware acceleration by `setRenderMode(RenderMode.SOFTWARE)` is useless.

Lottie Compose version: `4.1.0`

Thanks in advance.

**Comment by YangX29** [comment]
Here is a simple project reproduces the issue.
[LottieTest.zip](https://github.com/airbnb/lottie-android/files/7230841/LottieTest.zip)

**Comment by YangX29** [comment]
The bug appeared in version `4.1.0`，and `3.4.1` works well.

**Comment by gpeal** [comment]
@YangX29 I'm not sure what, exactly you're seeing but I'm seeing onDestroy get called at the exact same time if I remove the animation in MainActivity entirely or if I leave it there. onDestroy always gets called a bit later but that shouldn't really affect anything.

Lottie is just a drawable drawing to a canvas at the end of the day so it shouldn't have any effect on activity lifecycles.

If you think otherwise, reopen this with a sample project that exhibits a clear difference in behavior that seems broken.
