### ISSUE TITLE
Lottie Cache Reflection

### ISSUE THREAD

**Issue by daihang1229** [airbnb/lottie-android#1937]
Hello dear:
   I am an android developer.Recently i had read source code about lottie.When i read LottieCompositionFactory#cache().Some question occured to me. 
   First,Create a LottieTask will produce a thread too, so why run taskCache.get(contiansKey) first.And why remove cache from Map(taskCache) after success/fail.

   Then, Why must be build a LottieTask for View,Actually LottieComposition is enough.

   Seek advice sincerely.

**Comment by gpeal** [comment]
@daihang1229 The task cache is implemented so that if you try and parse the same animation multiple times before it finishes parsing, all requests will join the same parsing task. For example, if you have an animation in a RecyclerView item and it gets requested 5 times right away, it will only get parsed once.

Once the task is completed, Lottie will rely on the LottieCompositionCache to retrieve the parsed composition.
