### ISSUE TITLE
Brittany

### ISSUE THREAD

**Issue by Mbrittny** [airbnb/lottie-android#1961]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WilbertClark** [comment]
First all I have an Android not iPhone I'm in the city Missouri Springfield
are from St Louis I'm a black male I understand the situation by patronize
and being penalized of being late about you guys policies policies and
informing me of when what how to spend no situation is I have people that
are nosy and due to my last experience of years back I have been in school
with the city because I was refused team to be treated as one as a slave
slash can donate maintenance and etc and since I don't obey when people
have been racist they found out that I really have a talent in the market
of investment exchange in stock so every bank account that I get and get
shut down everything counted I get with routing number I take the agreement
to the front desk of the bank it gets shuts down I'm here with my mom just
visiting hopefully I have better luck out of town please please please
please don't deny me what's owed to me because I am really having problem
with racism with the community of Springfield podcast broadcast when
they're feeling safe of people screaming chainsaws and all they are saying
that it's too much money for a n***** to have in that words sorry that I
have been respond back to you guys accordingly to the messages but they
also have a T-Mobile branch and other cellular phones company branches down
here that allows them to get on the main base of the computer and type and
take out whatever they have using that for somewhat what they call a
starship I have been shipped to jail numerous times and they know that my
phone is reliable source of my stocks exchange investments so they take
copy or steal from Banks or give me my emails late to be penalized or
extortion saying that they have my family friends etc dog text bugs mites
whatever so this is what I'm going through and believe me that it's a lot
of money to waste on nothing without cause I have been poor all my life
they said that I'm a hustler as I'm a drug dealer a drug abuser I do the
weirdest things to keep myself safe like acting like I assume acting like I
sell drugs acting like I even smoke drugs just to get a feel of the people
out there around because I do get bored as a human being so it was told to
me that that FBI here or building a case on me who they call a drug lord
that I am not so that touch basis this is an informal verbally and written
announcement that what I am going through is truly without you guys
understanding only hearing or texting or emailing etc the response of my
translated thoughts to your response of what why I have not got a contact
with you think you
