### ISSUE TITLE
Lottie doesn't support layer effects

### ISSUE THREAD

**Issue by aytunch** [airbnb/lottie-android#1964]
I get a warning saying 

> flutter: LOTTIE WARNING: Lottie doesn't support layer effects. If you are using them for  fills, strokes, trim paths etc. then try adding them directly as contents  in your shape. Found: [Stroke]

I tried using trim paths instead of stroke start/end but still same result.

I understand that mobile lottie does not support some layer effects. However in the warning it says:

> then try adding them directly as contents  in your shape

But I could not find any information on how to do this? Can you please tell me if there is a way to make these layer effects work in AE?

**Comment by gpeal** [comment]
Most layer affects are not supported. Some may be added over time but many are not practically achievable on Android.

It looks like you are using Stroke though. Strokes can be added in a similar way to a fill instead of using a layer effect.
https://animatestudios.com/blog/tutorial-animate-the-outline-of-a-word

**Comment by Jigar-zest** [comment]
Any update on this?

**Comment by lyle-luan** [comment]
> Most layer affects are not supported. Some may be added over time but many are not practically achievable on Android.
> 
> It looks like you are using Stroke though. Strokes can be added in a similar way to a fill instead of using a layer effect. https://animatestudios.com/blog/tutorial-animate-the-outline-of-a-word

animatestudios.com is not avaliable now.
