### ISSUE TITLE
Lottie in Android Splash API for android 12>

### ISSUE THREAD

**Issue by taouichaimaa** [airbnb/lottie-android#2010]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Is your feature request related to a problem? Please describe.**
Android dropped its Splash Screen API however Lottie files and animations are not supported, any tips to implement it using the api? 

**Describe the solution you'd like**
A way for lottie animations to be used in the android splash screen API for android 12>

**Describe alternatives you've considered**
there is a roundway [here](https://github.com/vcaen/splashscreen-sample) but it's too complicated ( cutting images from the animation into svg..)

**Additional context**

**Comment by gpeal** [comment]
SplashScreenView extends FrameLayout. Maybe you could use a custom enter/exit animation to add a `LottieAnimationView` or something. It is unlikely you'll be able to get the middle part of the splash screen to animate with Lottie. It likely supports AVDs because they animate on the render thread whereas Lottie animates on the main thread which will likely be busy initializing your app.

Ultimately, this is something you'll have to dig into more with splash screens and is unlikely something lottie-android will be able to build support for out of the box

https://developer.android.com/guide/topics/ui/splash-screen#customize-animation
