### ISSUE TITLE
LottieDrawable does not respect ANIMATOR_DURATION_SCALE

### ISSUE THREAD

**Issue by renard314** [airbnb/lottie-android#2052]
**Is your feature request related to a problem? Please describe.**
Hi Lottie Team, we are using LottieDrawable in our project as well as snapshot tests. We found that LottieDrawable does not respect the system animation settings like LottieView does. It has a package private `setSystemAnimationsAreEnabled` method that if it were public would allow us to disable Lottie animations for our snapshot tests.

I'm happy to open a PR if you agree that this issue should be fixed.

**Describe the solution you'd like**
make `LottieDrawable#setSystemAnimationsAreEnabled` public

**Describe alternatives you've considered**
Refactor LottieDrawable to check for system animation settings itself but it would need a context parameter in its constructor or additional work because `LottieDrawable#getContext` is nullable

**Additional context**

**Comment by gpeal** [comment]
@renard314 Can you set up your emulator with something [like this](https://medium.com/@balachandarkm/disable-animations-while-running-android-ui-tests-2d1748280156)?

**Comment by gsavvid** [comment]
@gpeal This doesn't work unfortunately because Lottie checks the value of the animation scale inside `LottieAnimationView` (in particular [here](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L212)) but not inside `LottieDrawable`. So if you use the latter, then those values are ignored and the animations run regardless.

**Comment by gpeal** [comment]
@gsavvid @renard314 Makes sense. I can un-restrict this API. Feel free to put up a PR too. If you do, update the javadocs for it.

**Comment by gsavvid** [comment]
I like the alternative that @renard314 suggested. It would be quite neat to let `LottieDrawable` take care of disabling animations based on the system settings and eliminate the need for additional configuration. Basically, it would look like this:

```
  public LottieDrawable() {
    ...
    setSystemAnimationsAreEnabled(Utils.getAnimationScale(getContext()) != 0f);
  }
```

The issue here is that `LottieDrawable#getContext()` is nullable. How would you feel about passing a context to the constructor, @gpeal? This would of course mean that we introduce a breaking change. Or do you have any other suggestions?

**Comment by gpeal** [comment]
@gsavvid You could start by creating your own wrapper around LottieDrawable that does this if you'd like. I could consider adding a special constructor for it if there are more requests.
