### ISSUE TITLE
Add Wear OS support? (Wear OS is pretty much Android at many levels)

### ISSUE THREAD

**Issue by Actualization** [airbnb/lottie-android#2129]
When adding lottie-android to a Wear OS 3 project in Android Studio it compiles well but adding any lottie elements to the view such as the basics examples in the documentation http://airbnb.io/lottie/#/android?id=from-xml
results in the error: ```Cannot resolve class com.airbnb.lottie.LottieAnimationView ```
WearOS appears to be a paired down Android with tweaks, developed in Android Studio using Android files and APIs.

#### To Reproduce
- Create two projects from Android Studio wizard via the file -> new menu.  One should be a "Phone" "Basic Activity".  The second should be a "WearOS" "Blank Activity".  
- Import lottie-android via the build.gradle file in both projects, they should both compile fine.  
- Adding a "com.airbnb.lottie.LottieAnimationView" View element to the layout of both. The Android one should work as expected while the WearOS one will return the file and compile error ```Cannot resolve class com.airbnb.lottie.LottieAnimationView ```.

I haven't been able to find any documentation on the web for using lottie on the new codebase of WearOS3 ( or earlier versions).  Google has been using WebP as an animation option on WearOS 3.

**Comment by gpeal** [comment]
The issue is that LottieAnimationView extends AppCompatImageView which isn't added as a dependency in wearOS by default. Add `implementation 'androidx.appcompat:appcompat:1.5.1'` (or whatever the latest version is) and it'll work.
<img width="1672" alt="CleanShot 2022-11-25 at 18 16 14@2x" src="https://user-images.githubusercontent.com/1307745/204068551-7719d347-3f79-4112-b4b9-d9e6e4c71ebf.png">
