### ISSUE TITLE
Target Layers for Touch Events

### ISSUE THREAD

**Issue by aminerol** [airbnb/lottie-android#2170]
**Is your feature request related to a problem? Please describe.**

right now theres no direct way to target a layer for touch events, we can hook to a value callback for `TRANSFORM_POSITION` and store that value for when a touch events is occurred and do a check if the touch intersects with value from the value callback. unfortunately couldn't achieve that knowing this is possible for iOS and found this [repo](https://github.com/YQqiang/LottieExtra/blob/803b139926c864bd39a9d58879994353825d86f8/LottieExtra/Classes/LottieExtraView.swift#L120) that do the exact same thing with a neat and straightforward API

**Describe the solution you'd like**

Would be really neat if we have some sort of callback but for touches, we can follow same api for value callback but with a touch callback that would be called if its touched. am thinking of something like that : 

```Java
animationView.addTouchCallback(keyPath, new LottieTouchCallback(() -> {
     // handle touch event here
 }));
```

**Describe alternatives you've considered**

i did tried to get the anchor point value as well as the transform point value and store it to be used later inside a `OnTouchListener` to know if touch intersects with transform & anchor point still not working, heres the code for it : 

```Java
class LottieLayer {
  PointF anchor;
  PointF position;

  public LottieLayer(PointF _anchor, PointF _position) {
    this.anchor = _anchor;
    this.position = _position;
  }
}

private HashMap<String, LottieLayer> layers = new HashMap<String, LottieLayer>();

animationView.setOnTouchListener(new View.OnTouchListener() {
        @Override
        public boolean onTouch(View _view, MotionEvent motionEvent) {
          if (motionEvent.getAction() == MotionEvent.ACTION_DOWN){
            PointF touchPoint = new PointF(motionEvent.getX(), motionEvent.getY());
            for (Map.Entry<String, LottieLayer> layer : layers.entrySet()){
              LottieLayer layerValue = layer.getValue();
              Float x = layerValue.position.x - layerValue.anchor.x;
              Float y = layerValue.position.y - layerValue.anchor.y;
              Float width = layerValue.anchor.x * 2;
              Float height = layerValue.anchor.y * 2;
              // check if touchPoint intersects with LottieLayer
            }
          }
          return true;
        }
 });

animationView.addValueCallback(
                keyPath,
                LottieProperty.TRANSFORM_POSITION,
                new LottieValueCallback<PointF>() {
                  @Override
                  public PointF getValue(LottieFrameInfo<PointF> frameInfo) {
                    LottieRelativePointValueCallback valueCallback = new LottieRelativePointValueCallback(new PointF());
                    PointF value = valueCallback.getValue(frameInfo);
                    LottieLayer oldValue = layers.get(path);
                    layers.put(path, new LottieLayer(oldValue != null ? oldValue.anchor : new PointF(), value));
                    return value;
                  }
                }
 );

 animationView.addValueCallback(
                keyPath,
                LottieProperty.TRANSFORM_ANCHOR_POINT,
                new LottieValueCallback<PointF>() {
                  @Override
                  public PointF getValue(LottieFrameInfo<PointF> frameInfo) {
                    LottieRelativePointValueCallback valueCallback = new LottieRelativePointValueCallback(new PointF());
                    PointF value = valueCallback.getValue(frameInfo);
                    LottieLayer oldValue = layers.get(path);
                    layers.put(path, new LottieLayer(value, oldValue != null ? oldValue.position : new PointF()));
                    return value;
                  }
                }
 );
```

**Additional context**

the missing piece for lottie is adding interactivity, its true its been done for some parts but in terms of firing events for some specific actions is missing. 
and for some cases we having lottie with multiple buttons in it and would like to target each for touch events and good example is this action button menu [https://lottiefiles.com/60073-action-button](https://lottiefiles.com/60073-action-button)

**Comment by gpeal** [comment]
I've been mulling over adding this off and on since your original request here. I think it could be _really_ cool for Lottie to support interactivity. However, I keep coming to the conclusion that there isn't a clean way to add this to the core Lottie library for the following reasons:
* At its core, Lottie is a drawable that knows nothing about touch events so they would need to be injected externally from something like LottieAnimationView or LottieAnimation in Compose. 
* Proper touch handling would require getting things like canceled events, multitouch, and accessibility right. Getting something that works for simple use cases is one thing but the bar is very high to be in the core library that anybody should be able to consume and use safely.
* If Lottie is used for UI, it should probably have a better layout engine to handle things like responsive sizes or text layout direction which would be clunky today. I've also mulled over what a constraint based layout engine might look like since ~2017 and haven't come up with anything that feels right there either.
* There hasn't been any other activity on this issue for the year it was open which leads me to believe that it isn't something a lot of people are looking for.

I would recommend creating your own wrapper on top of the dynamic property APIs and see how far you can get. Hopefully you can achieve what you want with that. If a smaller targeted API is needed to make that possible, feel free to reopen this with a specific proposal.
