### ISSUE TITLE
Lazy LottieAnimationView not working after onPause

### ISSUE THREAD

**Issue by ALLABER** [airbnb/lottie-android#2327]
I am using the library 'com.airbnb.android:lottie:6.0.1', Pixel 6a device, Android 13.

When returning from a fragment, the animation stops working due to lazy initialization of LottieAnimationView.

Here is an example of code:
`class FragmentOne : Fragment() {

    private lateinit var binding: FragmentOneBinding

    private val lottieAnimationViewStarLazy by lazy { binding.lavStar }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        binding = FragmentOneBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        initListeners()
    }

    private fun initListeners() {
        initButtonStartAnimationListener()
        initButtonNextFragmentListener()
    }

    private fun initButtonStartAnimationListener() {
        binding.buttonStartAnimation.setOnClickListener {
            lottieAnimationViewStarLazy.setAnimation(R.raw.anim_star)
            lottieAnimationViewStarLazy.playAnimation()
        }
    }

    private fun initButtonNextFragmentListener() {
        binding.buttonNextFragment.setOnClickListener {
            openTwoFragment()
        }
    }

    private fun openTwoFragment() {
        parentFragmentManager.beginTransaction()
            .replace(R.id.fcvRoot, FragmentTwo.newInstance())
            .addToBackStack(FragmentOne::class.java.name)
            .commit()
    }

    companion object {
        fun newInstance() = FragmentOne()
    }
}`

Here is the link to the repository: https://github.com/ALLABER/LottieBugExample

**Comment by gpeal** [comment]
Your problem actually isn't Lottie related. What's happening here is:
1. When you launch FragmentTwo, FragmentOne goes through onDestroyView
2. When you return to FragmentOne, it goes back through onViewCreated and inflates a new instance of the view hierarchy
3. `lottieAnimationViewStarLazy` retained a reference to the first LottieAnimationView because with `lazy`, once it's set, it won't update.

Simply changing the `lazy` to `private val lottieAnimationViewStarLazy get() = binding.lavStar` fixes the problem.
