### ISSUE TITLE
Animation stops after turning screen off and on. 

### ISSUE THREAD

**Issue by Drjacky** [airbnb/lottie-android#2431]
**Link to fork with a repro in the issue-repro module**
https://github.com/Drjacky/MVVMTemplate/issues/56

**Describe the bug**
Animation stops after turning the screen off and on. 

**Steps To Reproduce**
Steps to reproduce the behaviour:

1. Disconnect the internet
2. Click on Coroutine Button
3. It displays the No Internet Lottie animation
4. Turn the screen off
5. Turn the screen on
6. There is no Lottie animation anymore!

I tested with Lottie 4.2.2 and 6.2.0 and it exists.

**Comment by gpeal** [comment]
Your problem actually has nothing to do with Lottie at all. If you notice, the "No internet" and retry button don't appear either.

Your issue is that you're using your `collectIn` function on `Flow<Failure>`. When you resume, your `productsListByCoroutine` flow emits paging data which then clears the loading ui. However, your failure flow never re-emits.

**Comment by Drjacky** [comment]
> and retry button don't appear either.

You're right!
__
The issue was one extra call on `loadingUI(false)` and misplace of `binding.inclItemError.itemErrorContainer.gone()`
