### ISSUE TITLE
Seeking Solutions: Lottie Animation Freezing Issue on Android 10 (Version 5.1.0)

### ISSUE THREAD

**Issue by j-mouellic** [airbnb/lottie-android#2463]
I am reaching out to bring to your attention a persistent issue with our Android application, specifically related to the Lottie animation.

Our application, running on Android 10, utilizes Lottie library version "5.1.0". We have noticed that the Lottie animation freezes at regular intervals, approximately every 1 to 2 minutes, causing a disruption in the user experience. Upon investigating, the following log message is consistently recorded:

Skipped 119 frames! The application may be doing too much work on its main thread. 

Despite a thorough review of our codebase, it appears that there are no ongoing operations on the main thread during these occurrences.

Additionally, it's worth noting that due to our current use of the free version, we have not opted for an optimized animation format. Could this limitation be contributing to the animation freezing issue?
My suspicion is that the Lottie animation itself might be causing this problem, is it possible ?

To provide you with more context, I have attached the three Lottie animations that we currently use. Strikingly, all three animations exhibit the freezing issue.

I wanted to seek your expertise on whether you have encountered similar issues with Lottie animations on Android 10, particularly with version "5.1.0". Moreover, any guidance on troubleshooting and resolving this issue, given the specific version and freezing frequency, would be immensely valuable.

Your assistance in resolving this matter is greatly appreciated. Thank you for your time and support.

**Comment by gpeal** [comment]
Sorry you are having performance issues but I would suggest using the [performance testing](https://airbnb.io/lottie/#/android?id=performance) documentation to see if you can further look into this for your specific use case.

Lottie Android is an open source library that isn't affiliated with Lottiefiles if that is what you are referring to with regards to a paid version. This library is open source and free of charge. You can, however, use GitHub sponsors (at the top of this repo) or [Open Collective](https://opencollective.com/lottie/) to sponsor the project.

If you'd like to do that, I may be able to carve out some time to look at your specific animations though.

I'm going to close this issue because it's not directly actionable though.
