### ISSUE TITLE
interaction issue

### ISSUE THREAD

**Issue by JachinGao** [airbnb/lottie-android#269]
Hi,
Recently i have been concerned about the great library,here are some ideas to discuss.

Will Lottie later can provide some APIs to increase interactivity? For example,I treat  LottieAnimationView as a container, each element of the animation is seen as a view, just like the relationship between ViewGroup and View. Then through the container,we can get each of the independent element in the animation. For each element, we can add some simple operations, such as rotation, transformation,scale, gradient and other animation effects.

In the follow-up version, whether Lottie team has considered adding similar features?

thanks!

**Comment by gpeal** [comment]
@JachinGao We don't plan on adding interactivity. However, you can split up the animation and use multiple LottieAnimationViews to achieve the same effect.

**Comment by wangdaliu** [comment]
@gpeal Hi, i have a demand, when pause the whole animation, some of the elements can continue with the animation.  Do you have any suggest? Thanks

**Comment by gpeal** [comment]
@wangdaliu Try breaking your animation into separate animations then just have the views overlap and control them individually.

**Comment by wangdaliu** [comment]
@gpeal Thanks for replying me, but my requirement may be a bit complicated. For example, the animation contains a man, the man keep moving. we want this person's eyes blinking according to a certain frequency(Including this man animation paused). Because the person's position keep changing, so it is difficult to achieve through overlap the view.  So now if can separate control animation seems to be the best choice for me. Thanks.

**Comment by nitin9096** [comment]
i  need one help i have json  file and there are multiple layers or componants and i need to handle click of the componants diffrently how can i do this?
