### ISSUE TITLE
Animation size

### ISSUE THREAD

**Issue by mare011** [airbnb/lottie-android#315]
Hi, I've been using beta-4 version for a few animations, I've tried switching to rc-1/rc-2 and all animations became tiny, like few pixels, i can't figure out witch change caused it. Thanks in advance.

[animation.zip](https://github.com/airbnb/lottie-android/files/1038485/animation.zip)

**Comment by gpeal** [comment]
@mare011 It renders fine in the lottie sample app. You can try setting the scale manually. See if that helps.

![screenshot_1496190227](https://cloud.githubusercontent.com/assets/1307745/26610513/c9a7ac7a-455c-11e7-8155-ca353947595f.png)

**Comment by mare011** [comment]
Setting the scale to 0.1 makes the animation the right size, it grows as i lower the scale, shouldn't it be opposite?

**Comment by gpeal** [comment]
@mare011 There must be something strange going on within your app's code. It seems to work fine in the lottie sample app.

**Comment by GrzegorzFeather** [comment]
Hi, I'm experiencing same issue with the following animation:
[onboard-animation.zip](https://github.com/airbnb/lottie-android/files/1042752/onboard-animation.zip)

When I scale down it works perfectly, but when start scaling up it gets smaller.

![screenshot_20170531-125526](https://cloud.githubusercontent.com/assets/3044632/26651181/b485940c-4600-11e7-8994-0e10499aadc3.png)
![screenshot_20170531-125540](https://cloud.githubusercontent.com/assets/3044632/26651180/b4841898-4600-11e7-8be4-a565e4785aae.png)

**Comment by gpeal** [comment]
@GrzegorzFeather Ah, the issue is that right now Lottie sets the max scale such that it can't be larger than the view itself (which will never be larger than the screen).

In this case, the bounds of the drawable keep growing but the drawing size stays the same so the effect of the centerInside scale type is that it appears to be shrinking.

**Comment by GrzegorzFeather** [comment]
@gpeal I see, so the reason I brought this up is because I noticed too that if I add the LottieAnimationView to match the screen size it's correctly scaled, but by adding margin to the start/end then this same behavior happens. Same thing if I put it inside a ViewGroup that does not match the screen size. This prevents me of resizing or even fit the view inside a container that does not match the screen width. Is this the expected behavior?

**Comment by gpeal** [comment]
It's likely that your composition is just too large to begin with. You can try a) asking your designer to make the composition size smaller (the composition size in px gets converted to dp by Lottie) or b) manually set the scale such that it's smaller than the view and using scaleType=centerInside

**Comment by gpeal** [comment]
@GrzegorzFeather

**Comment by GrzegorzFeather** [comment]
@gpeal makes sense, will try that approach. Thanks for the help!

**Comment by mare011** [comment]
Yep, mine problem was that i had set 40dp width and height. So designers should then create the animation in mdpi, my current image is xxxhdpi? But then the image will be small for higher dpi devices, right? Or the images should be, in this case 160x160, and the animation itself 40x40? What i don't get is how setting the scale to 0.1 gives the right size, it would makes sense that 0.25 would do it, because of x4 dpi, but it doesn't. Settings the scale to 0.1 makes every animation look like in beta.4 version.

**Comment by gpeal** [comment]
@mare011 One of the disadvantages of using images in Lottie is the inability to use resource buckets. They will be rendered at the dp equivalent of their pixel size. You can export higher density images and scale it down on the layer's transform.
