### ISSUE TITLE
About FPS fluency problem

### ISSUE THREAD

**Issue by wyfang** [airbnb/lottie-android#329]
Hello everyone, first use, some questions about animation fps.
At the beginning, I used png picture ae project used to test and found fps very low, very consumption of mobile phone resources, Click here to view my recorded videos: https://youtu.be/0QK-X3GkAQk

Then I made a circle, very simple animation, but still feel fps is not high, so is not where I do wrong? Export? Export I use the default option, nothing changes.
[very simple animation ae.zip](https://github.com/airbnb/lottie-android/files/1060414/ae.aep.zip)

**Comment by gpeal** [comment]
@wyfang if you are using images, [turn on hardware acceleration ](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L270).

However, that animation doesn't look like it would need pngs. Lottie will be much faster and more efficient if you can use shape layers. If you're importing After Effects layers, convert them to shape layers rather than using exported pngs.

**Comment by gpeal** [comment]
@wyfang Also, the complexity of your animation will affect the performance. The lottie logo is much more complex than the watermelon due to its extensive use of trim paths.
