### ISSUE TITLE
Hardware automatic recognition

### ISSUE THREAD

**Issue by talentqing** [airbnb/lottie-android#381]
Can you according to the features of animation to decide use hardware? Because most animations is so simple and no hardware porblem, if any animation use software will be stuck when the ui is complex and the mobile phone performance is bad.

for exmaple:
[test.zip](https://github.com/airbnb/lottie-android/files/1143984/test.zip)
this animation in hardware is performance obviously better than in software.

So I thing can according to the api of features and phone info to auto decide use hardware or software.

**Comment by gpeal** [comment]
Yup, it's been on my mind to do something like this!

**Comment by talentqing** [comment]
Do you plan to add this feature in the next release?

**Comment by gpeal** [comment]
@talentqing Not sure, maybe.

**Comment by gpeal** [comment]
@talentqing You can enable it manually today though.

**Comment by AndroidDeveloperLB** [comment]
@gpeal But how could we know when it's safe to enable it?
According to what I've found (written about it [here](https://github.com/airbnb/lottie-android/issues/682)) , I think it's safe to use it starting from Android L (API 21)

**Comment by gpeal** [comment]
I've decided to not do this because some animations perform much worse with hardware acceleration even when it supports it. It should continue to be used on a case by case basis.

**Comment by gpeal** [comment]
http://airbnb.io/lottie/android/performance.html#hardware-acceleration

**Comment by AndroidDeveloperLB** [comment]
@gpeal Can you please provide an example (animation file) that enabling hardware acceleration makes it perform worse?
Also, do you really thing the default behavior, of having it disabled - is usually performing better ?
If not, why having this as the default behavior?
After all, even choosing not to do anything still have a default behavior, which is having it disabled.
This was the case on Android too: for some time, hardware acceleration was disabled by default, and starting from certain Android version, it became enabled by default. Developers can still disable it if they want.

**Comment by gpeal** [comment]
@AndroidDeveloperLB Please [read the article](http://blog.danlew.net/2015/10/20/using-hardware-layers-to-improve-animation-performance/) linked to in the docs. 
There are also cases where certain phones have GAIA bugs that cause things to render incorrectly with hardware acceleration even if they are supported. Facebook stopped using hardware acceleration to render reactions for this exact reason. That's why it's disabled by default. It's easy to enable though so feel free to use it if it works well for you.

**Comment by AndroidDeveloperLB** [comment]
This article is very old, and I've read it already. In fact some of my comments are there.

Question is, if it's safe to use now starting from certain Android version, why not enable by default?
I've noticed it's so slow (frame skips) on some cases without hardware acceleration. 

Do you think the " GAIA bugs" still occur on today's smartphones?  Even on Android 5, 6, 7, 8 ... ? 
Can you please show an example of an animation file that has issues on such Android versions, when HA is enabled ? 
For us, we've decided to enable it from Android 5, because of how slow it can be without HA enabled, but if you show me an animation file that shows issues on smartphones of these versions, we should re-consider even using this library, because we can't afford having slow animations.

**Comment by AndroidDeveloperLB** [comment]
@gpeal What's the logic you've chosen on your apps that use Lottie, of determining when to enable HA and when to disable it ? 
It's impractical to test on all devices, so I think you've chosen some arbitrary solution, right?

**Comment by gpeal** [comment]
@talentqing I'm going to re-investigate this.

**Comment by gpeal** [comment]
Fixed by #1048

**Comment by AndroidDeveloperLB** [comment]
@gpeal So no need anymore for this API of enabling HA ?

**Comment by gpeal** [comment]
@AndroidDeveloperLB Correct, this will now be automatic and no manual work will be needed. The existing APIs were also removed. It will be in the next version that I'm preparing. Stay tuned. Not sure if it will be 2.9 or 3.0.

**Comment by AndroidDeveloperLB** [comment]
@gpeal Good. Last time you were pessimistic about when I should enable it. :)
