### ISSUE TITLE
Animation borders wrong when size is set fixed

### ISSUE THREAD

**Issue by PaulWoitaschek** [airbnb/lottie-android#404]
When I set an animation our designer created in the lottie preview app, everyhing works fine. 

But when I set the dimension of the view to fixed bounds (like 100dpx100dp, even with the right aspect ratio), the layers of the animation are totally off.

I'm sending the images to your mail right now.

**Comment by PaulWoitaschek** [comment]
What's weird is that by setting the scale factor to 0.1 it's working like expected.

**Comment by gpeal** [comment]
@PaulWoitaschek Views with a mask or matte can't be larger than the view and yours are 108x150. I'm currently trying to add some guards to prevent this particular case from happening though

**Comment by PaulWoitaschek** [comment]
So that means in as future version it will work anyways?
And why does setting the scale fix the animation?

**Comment by gpeal** [comment]
@PaulWoitaschek Setting the scale fixes it because it scales down the animation such that the mask and matte are no longer larger than the image. ImageView then re-scales it back up with centerInside. If you turn on hardware acceleration, you will probably see some pixelation if you do that though. In your case, the best thing to do is to ask your designer to make the composition 100px tall so that it's intrinsic size is 100dp in Lottie. It's 150 right now which means that setting the scale to 0.66 will have a similar effect (although may be every so slightly less performant than actually fixing the comp size).

**Comment by PaulWoitaschek** [comment]
Thanks, that worked. What about adding a section where you describe these common issues & how to fix them?

**Comment by gpeal** [comment]
@PaulWoitaschek I was actually able to solve this yesterday with the commit referenced above. It shouldn't be an issue after the next release :)

**Comment by PaulWoitaschek** [comment]
But didn't you say this will cause pixelation?

**Comment by gpeal** [comment]
Only if you scale it up significantly *and* are using hardware acceleration. There isn't a way around that without taking a huge performance hit.

**Comment by gpeal** [comment]
@PaulWoitaschek 2.1.2 is out

**Comment by PaulWoitaschek** [comment]
![lottie](https://user-images.githubusercontent.com/743462/28862807-c4c6aeae-7766-11e7-9ee3-d7d4f529b9e7.png)
Thanks. I think this caused other errors now in 2.1.2. When I set the width fixed and the height to wrap_content, my animations are cut off now.
The sample app has some scaling issues now, for example watch `Hello World.json`. In the default scale of 1.0, the text is cut off inside the bounds.
