### ISSUE TITLE
Lottie animation is not working when close Animation in developer options

### ISSUE THREAD

**Issue by johanlin** [airbnb/lottie-android#417]
When I close animation like this, lottie don't work anymore.
![image](https://user-images.githubusercontent.com/8087423/28867977-8be8c10a-77aa-11e7-8da6-b8ad500887f7.png)
In this situation, how can i do to make it work

**Comment by gpeal** [comment]
@johanlin This is intentional (https://github.com/airbnb/lottie-android/blob/fcdac57b1918fb500d10f21bba7a02b8a8b597a1/lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java#L63(. Lottie will show the last frame of the animation in this case.
If you want to make this work, create your own ValueAnimator from scratch since the system ValueAnimator will just call onEnd immediately and call setProgress on your own.
