### ISSUE TITLE
LottieComposition#fromAssetFileName() method should throw exception

### ISSUE THREAD

**Issue by IonutNegru87** [airbnb/lottie-android#515]
If the fileName parameter is not valid, this method will throw an IllegalStateException, but the actual method does not throw that exception.
I think the method should be updated to actually throw the exception to avoid any confusion.

**Comment by gpeal** [comment]
@IonutNegru87 Since this is not an expected error and if used properly, this method will never throw, it wouldn't be a clean API to require every single consumer of logic to explicitly handle this unexpected failure case. If you need to wrap it for some reason specific to your application, feel free to do that.

Also feel free to reopen this if you disagree with that.
