### ISSUE TITLE
Missing company name and year from LICENSE file

### ISSUE THREAD

**Issue by anthonymonori** [airbnb/lottie-android#527]
I was looking through the LICENSE file and was wondering why the year and the company name has been left out when placing the the ASL2.0 license template.

https://github.com/airbnb/lottie-android/blob/cc4107c4e63d90e934c384caa9ad28c5f22df9c6/LICENSE#L189

I am planning to showcase the OS licenses for the 3rd party libraries I use in my own app, and wondering if this is legally binding or is it just a mistake that you may want to correct?

**Comment by gpeal** [comment]
Good catch @anthonymonori.

**Comment by JakeWharton** [comment]
This change is incorrect. The part of the license you changed was the template which instructs you how to apply the license. You are not meant to change it, since it's intentionally a template.

**Comment by JakeWharton** [comment]
It's not a huge deal, by the way. I only noticed when trying to automate validating your license. You don't point at the canonical one (http://www.apache.org/licenses/LICENSE-2.0.txt or https://www.apache.org/licenses/LICENSE-2.0.txt) in your pom and your custom URL does not match any known text (because of this change). It's funny because it weirdly came up on one of our projects two days ago: https://github.com/square/kotlinpoet/issues/1077.

We have mechanisms to manually approve this project, but I would just consider reverting the commit. And if you want, consider changing the pom to point to one of the canonical URLs to help automated tools.

Actually, another thing that changed recently is that [the Maven POM specification actually recommends using a SPDX identifier](https://maven.apache.org/pom.html#Licenses) as the `<name>`. We're going to change all our projects, so while you're mucking around you could consider that too (it would be "Apache-2.0"). But thus far I've found literally zero projects that do it.

**Comment by gpeal** [comment]
Thanks for the info @JakeWharton!

**Comment by syleeeee** [comment]
But I still think open source projects should specify copyright holder information.
[In ASF homepage](https://www.apache.org/licenses/LICENSE-2.0#apply) it says,
> replacing the fields enclosed by brackets "[]" with your own identifying information. (Don't include the brackets!)

**Comment by JakeWharton** [comment]
Sure, but this is not the place. This is the template for how to apply the license and not an actual place where copyright applies. Consult your lawyers and they'll say the same.
