### ISSUE TITLE
Animations are buggy

### ISSUE THREAD

**Issue by alexandrharchuk** [airbnb/lottie-android#545]
Dear Gabriel Peal!
I am using your com.airbnb.android:lottie:2.2.5 library for animation. I have 3 animations in total, each of them is on a separate fragment (I use the tutorial library com.github.apl-devs: appintro: v4.2.2). But the problem is that the animations are buggy. Each animation contains approximately 100 frames. The size of one animation with such number of frames in png format is approximately 3-5 megabytes. Would you be so kind suggest how can i optimize these animations.

**Comment by gpeal** [comment]
@alexandrharchuk I'm confused as to what your issue is. Are you using pngs with Lottie or are you comparing the equivalent animation using png sequences?

Is the actual rendering of the animation itself buggy?

**Comment by alexandrharchuk** [comment]
[animations.zip](https://github.com/airbnb/lottie-android/files/1530611/animations.zip)
I have design elements in png, but I animate with the standard tools of after effects and export it into json + png. Animation is displayed without errors.

**Comment by gpeal** [comment]
I just loaded these in the sample app and they seemed to render fine.

As a side note, Lottie is much better when all of your assets are in vector format (shape layers in After Effects) rather than pngs. If these are from illustrator, follow our guide [here](http://airbnb.io/lottie/after-effects/artwork-to-lottie-walkthrough.html)
