### ISSUE TITLE
how can i release graphics memory in lottie 

### ISSUE THREAD

**Issue by 456838** [airbnb/lottie-android#546]
after i load one json file in lottie , my memory still keeping high more than 135m、which graphics contains more than 70m . it was terroies!  can i get help ? 
if there some method i can call to solve?

![](https://i.imgur.com/hILbySH.png)

**Comment by gpeal** [comment]
@456838 Can you attach the animation you're trying to load?

**Comment by gpeal** [comment]
Lottie by itself doesn't use any graphics memory. Here is my memory graph before and after loading an animation. If it's because you have a ton of images in your animation, try using vectors instead.

![image](https://user-images.githubusercontent.com/1307745/34011555-6c53bf82-e0de-11e7-95a2-444d730c17e4.png)

**Comment by 456838** [comment]
how can i release this images by lottie?

**Comment by 456838** [comment]
or can we has new strategy for image loader? such as fresco , uil ,glide?

**Comment by gpeal** [comment]
@456838 Call `updateBitmap(yourImg, null)` to clear the cache for a given image. This is a bandaid on a larger problem which is that your animation has too many images.

**Comment by gpeal** [comment]
You shouldn't have to load bitmaps in and out of memory during the animation just to make it run
