### ISSUE TITLE
setScaleType() method not work

### ISSUE THREAD

**Issue by leleliu008** [airbnb/lottie-android#550]
I use version of lottie-android library is 2.3.1，my compisition is all images，all image size is 375x667px，my Android device's resolution is 720x1920px，my LottieAnimationView's config as follow:

`<com.airbnb.lottie.LottieAnimationView
                android:id="@+id/activity_watch_live_lottie_animation_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>
`
but, all iamges is always in left-left conner, No matter how I call setScaleType().

**Comment by gpeal** [comment]
@leleliu008 Can you post your animation?

**Comment by leleliu008** [comment]
my animation : [https://raw.githubusercontent.com/leleliu008/android_query_0.25.10/master/58.zip](url)

**Comment by leleliu008** [comment]
only lottieAnimationView.setScaleType(ImageView.ScaleType.MATRIX); is work

**Comment by gpeal** [comment]
I just tried centerInside and centerCrop on your animation using the sample app in the repo and it seems to work fine so the issue is probably somewhere else.
<img width="562" alt="centerinside" src="https://user-images.githubusercontent.com/1307745/34011847-851e68cc-e0df-11e7-800f-eade4ee6cf00.png">
<img width="562" alt="centercrop" src="https://user-images.githubusercontent.com/1307745/34011848-852acb4e-e0df-11e7-97e6-345b6e77b4d5.png">
