### ISSUE TITLE
Can only enable/disable trace between frame draws.

### ISSUE THREAD

**Issue by azchohfi** [airbnb/lottie-android#569]
setTraceEnabled can only be called between frames.
In that method (https://github.com/airbnb/lottie-android/blob/2df1c2bac1cb886dce38d64e0b3a80d603e8dc51/lottie/src/main/java/com/airbnb/lottie/L.java#L24), it changes the instance of the sections and startTimeNs variables, making a next call to endSection throw due to traceDepth == -1.

One possible fix is to delay the sections and startTimeNs recreation to occur only when traceDepth is 0.

**Comment by gpeal** [comment]
@azchohfi Why are you enabling the traces in the middle of animating?

**Comment by azchohfi** [comment]
I'm just toggling it on/off with a button click.

**Comment by gpeal** [comment]
@azchohfi That wouldn't be enough because then it would crash when it tries to end a section at a shallower depth than when you started tracing. Why do you need UI to enable/disable systrace markers? I suggest either just enabling them as a one off build or in your application code, pause the animation and post the maker enable call.

**Comment by azchohfi** [comment]
That's actually the bug I'm facing right now. I've already ported this code to LottieUWP a while ago, so I was just trying to keep it updated with the Android source. If that's a "by design" scenario, then I'll change it in the C# code.

**Comment by azchohfi** [comment]
In case you want to support this on Lottie Android, this is the C# version: https://github.com/azchohfi/LottieUWP/commit/acdb1e338fb0cbbc516e43653ce54beede210b73
