### ISSUE TITLE
Pre-composition support

### ISSUE THREAD

**Issue by stewjacks** [airbnb/lottie-android#61]
Quite a few of our animations are pre-comp'd as we reuse elements. Bodymovin supports them; Am I doing something wrong and/or is this on the roadmap for Lottie? I'm game to look into it.

**Comment by gpeal** [comment]
We don't support precomps yet but it's something I'm very actively looking into adding! Stay tuned!

**Comment by qmetzler-luna** [comment]
Still not fully working for my animation but I can definitely see some improvement. Do I still need to wait for the support of something more or is it related?
(I paid a set of animation so I don't really know how they're done.)

[adin.zip](https://github.com/airbnb/lottie-android/files/787029/adin.zip)
(rename adin.zip into  adin.aep)

**Comment by gpeal** [comment]
@qmetzler-luna You'll have to checkout the repo and rebase to check the latest change.
I'm actually using yours as a test for some things right now. There are a few reasons yours still isn't working but I hope to get to them soon. Stay tuned.

**Comment by gpeal** [comment]
@qmetzler-luna  @stewjacks  1.5.0 is now out!

**Comment by stewjacks** [comment]
@gpeal Awesome! I'll play with it today ✌️

**Comment by gpeal** [comment]
@qmetzler-luna yeah I think there may still be a few minor things. I have your AE file though so I'll continue to use it as a benchmark.

@stewjacks Great, if you have any issues, can you send me your AE file at lottie@airbnb.com?

**Comment by qmetzler-luna** [comment]
@gpeal lots of my animation are working smoothly, thanks for the update. One does not work at all, I'll send it to you tomorrow.
But for all of them if I use let say 75dp as height and width instead of wrap_content only the top left part seems to animate correctly.

**Comment by gpeal** [comment]
@qmetzler-luna Can you send me one where only the top left animates correctly?
My screenshot tests seem to be doing that but I haven't actually seen that happen on a device so I'd like to figure out what's going on there.

**Comment by qmetzler-luna** [comment]
@gpeal actually the one I sent you is doing it

**Comment by qmetzler-luna** [comment]
@gpeal Here are three aep files samples of the one not fully working for me. Appart from the top left issue that they all have, "atom.aep" has some masking issue I suppose (I have several animation with the same issue), "car.aep" has the wheels not animating and "stadium.aep" isn't working at all but bodymovin can't make it work either.
[lottie.zip](https://github.com/airbnb/lottie-android/files/796329/lottie.zip)

**Comment by therealsalih** [comment]
Hi @qmetzler-luna there are a couple of things in your files that i've noticed that we're still currently working on.

Atom.aep - we dont yet fully support fill rules. So instead of the multiple paths being cut through they just get added.
<img width="357" alt="screen shot 2017-02-23 at 8 31 21 am" src="https://cloud.githubusercontent.com/assets/5893643/23268428/8cc02af4-f9a2-11e6-80f4-69bbd8d7944d.png">


Car.aep - Neither bodymovin nor Lottie supports layer styles at the moment
<img width="434" alt="screen shot 2017-02-23 at 8 35 31 am" src="https://cloud.githubusercontent.com/assets/5893643/23268597/1760d50a-f9a3-11e6-9472-4911e82293a7.png">

Also you're using some expressions in ehre that Lottie doesnt yet support
<img width="891" alt="screen shot 2017-02-23 at 8 36 08 am" src="https://cloud.githubusercontent.com/assets/5893643/23268622/286eefe4-f9a3-11e6-909a-eed6abbd6733.png">


Stadium.aep file. Neither Bodymovin nor Lottie supports layer styles at the moment. You can achieve that same stroke by just using a stroke inside the shape layer

<img width="461" alt="screen shot 2017-02-23 at 7 59 33 am" src="https://cloud.githubusercontent.com/assets/5893643/23266919/09aec7dc-f99e-11e6-9b73-bc95ebe0fa80.png">

**Comment by stewjacks** [comment]
This seems to be working for me. We originally had issues with assets exported from Illustrator, but we've been going through and deleting merge paths as well as all the random groups created when importing... and everything seems to be honky dory now. Thanks!

**Comment by gpeal** [comment]
@qmetzler-luna track #158 for fill types
@stewjacks Great to hear!

**Comment by qmetzler-luna** [comment]
@therealsalih Thanks for the precision! @gpeal And for the size of the animations? You can test it by setting 75dp instead of wrap_content in the demo project and load the first animation I sent you.

**Comment by gpeal** [comment]
@qmetzler-luna I can see your issue. I'll investigate it and track the progress in #161

**Comment by fentonbutcher** [comment]
@gpeal For some reason, I can't get a pre-comp to work in my file. It exports from after effects fine but doesn't show up in ios

**Comment by gpeal** [comment]
@fentonbutcher Can you post the issue on lottie-ios then?

**Comment by guaard** [comment]
Hello, I have a problem when I do the exportation. I have only a fix background ...
I think is related to my precomps. I have the version 5.3.4.
Thank you in advance for your help !

[test.aep.zip](https://github.com/airbnb/lottie-android/files/2764311/test.aep.zip)
