### ISSUE TITLE
Frame Drop

### ISSUE THREAD

**Issue by cshalysongoncalves** [airbnb/lottie-android#647]
@gpeal  My animations are dropped frame. Currently I have an onboarding screen in which it has four 4, each with an animation.

*Pixel 1 - Android Oreo
*Lottie 2.5.0
[raw.zip.zip](https://github.com/airbnb/lottie-android/files/1749837/raw.zip.zip)

**Comment by cshalysongoncalves** [comment]
The animation is catching (league)

**Comment by gpeal** [comment]
@cshalysongoncalves Sorry, I don't understand.

**Comment by nabrozidhs** [comment]
From what just happened to me I guess something changed from `lottie:2.5.0-rc1` to `lottie:2.5.0` and is causing the same animation to look like is dropping frames.

**Comment by gpeal** [comment]
@nabrozidhs Lottie now respects the framerate set in After Effects instead of trying to render everything at 60fps. I can add an API to force it to try and render at 60fps if you want though.

**Comment by nabrozidhs** [comment]
I don't think it's needed, I'll ping my designer and update my source animations. 

I'll let you know if it works!

**Comment by cshalysongoncalves** [comment]
Exactly as @nabrozidhs mentioned!

**Comment by azchohfi** [comment]
I did this for LottieUWP. It now has a FrameRate property that by default has the value set inside the main file, but it can be changed by the developer, if wanted.

**Comment by cshalysongoncalves** [comment]
@gpeal Any news?

**Comment by gpeal** [comment]
I will add this in the next few weeks or will accept a pr sooner.

**Comment by Akshshr** [comment]
Hey, 
Running this on Motorola Play Z, and I see a lot of lag/dropped frames in every animation.

Dont think this issue is device specific, but it appears lottie as a library isnt very friendly to phones that are slightly older.

Needs to be lighter as far as I can tell, do you guys have any suggestion?

**Comment by gpeal** [comment]
@Akshshr I think any dropped frames regression in 2.5.0 is actually due to it following the framerate specified in After Effects rather than trying to always run at 60fps. I may revert this behavior change, however.

Lottie was written with performance in mind. However, many performance issues can be solved by re-working parts of your animation, particularly if they have many or large mattes or masks. There are some suggestions [here](http://airbnb.io/lottie/android/performance.html). If there are opportunities to improve lottie itself, feel free to open a pull request.

**Comment by Akshshr** [comment]
@gpeal  Hey, thanks for that! looks like it was my test device that was causing some trouble, phone just needed a restart! 
Thanks for the help anyway

**Comment by Umar3x** [comment]
@gpeal  Im having a similar issue. On android, when displaying more than 4 lotties at the same time, there is a massive fps drop on the app that I don't meet on iOS with same animation. Ive got not warning at all, the animation was designed by a designer that followed what need to be done to have a smooth animation. Btw, with one or two animations its perfectly smooth.
I know my test device is not a S9, its a honor 9 , but it runs a lot of games that are much more greedy if I may say than  4 lotties animation.

**Comment by gpeal** [comment]
@Umar3x please try 3.0.0-beta1

**Comment by Umar3x** [comment]
@gpeal  

Can't do that, cause I'm on Xamarin .NET and 3.0.0-beta1 not available on this package. Just one question, what could cause that in actual version, if may be fixed in 3.0.0-beta1 ?

**Comment by gpeal** [comment]
@gpeal Mattes and masks are 2-10x faster with 3.0

**Comment by gpeal** [comment]
@zhangwenjia616 There is not as most mobile apps are expected to run at the refresh rate of the display (usually 60, 90, or 120hz). Animations that play at 24/30fps often look laggy in comparison. What is your use case for wanting that?

**Comment by zhangwenjia616** [comment]
@gpeal is there any api like iOS‘s `AnimationView.respectAnimationFrameRate`
or web's `anim.setSubframe(boolean)` for android side, so we can respect the animation frame rate setting in the AE?

**Comment by zhangwenjia616** [comment]
@gpeal some Lottie file our designer give me runs flickering in both iOS and android, and after setting `AnimationView.respectAnimationFrameRate`, iOS side looks good. 
but for android side, do we have the same api?
