### ISSUE TITLE
Animation not same on iOs and Android. Animation reversed. Rotated 180

### ISSUE THREAD

**Issue by fredydoss** [airbnb/lottie-android#652]
I have a custom progress bar and it does not behave the same on Android and iOs. 

On iOs it rotates clockwise(desired direction) but on android it is completely the opposite.
The rotation is anti-clockwise and it is rotated 180degree.

I used the com.airbnb.android:lottie:2.5.0-rc1 to use the setSpeed(-1) to reverse the animation. 
Even the setSpeed(-1) is not working on the stable version.

**Comment by gpeal** [comment]
@fredydoss Can you attach the animation?

**Comment by fredydoss** [comment]
@gpeal  It works well on iOs but not on android <br> 
[test.json.zip](https://github.com/airbnb/lottie-android/files/1771630/test.json.zip)

**Comment by gpeal** [comment]
@fredydoss For the trim path in your animation, I see:
offset: 178 degrees
Start: 51% -> 0%
End: 100% -> 0%

Based on this, I would expect it to go counter clockwise and just confirmed that in After Effects. If you think otherwise, can you attach the aep file?

I also tried reversing the speed which correctly made it go clockwise.

I did, however fix looping while the animation speed is reversed here https://github.com/airbnb/lottie-android/commit/f886de12309badd31e3298e7e33f94c8ffa2425d
