### ISSUE TITLE
MergePaths bug for LottieFiles:motorcycle.json

### ISSUE THREAD

**Issue by dnfield** [airbnb/lottie-android#665]
Using this file: 
https://www.lottiefiles.com/29-motorcycle

with merge paths enabled on a KitKat+ phone in Lottie preview, the motorcycle doesn't render properly.  Something seems to go off with the PathOp.Intersect.  

I'm finding this while working on a Flutter port of Lottie that's largely based off of the Android code.  It renders fine if I force it to go to PathOp.Union.  It makes me suspect there may be an issue with the parsing of the MergeModes - is this documented somewhere?  In https://github.com/airbnb/lottie-web/blob/76032ed287004dbef90f08fa3b30d0c896f2da3c/docs/json/shapes/merge.json it's just listed as "number".

**Comment by gpeal** [comment]
@dnfield I'm not sure that the lottie merge paths 100% map the AE ones. In fact, it's possible that there are some inconsistencies. This is where the logic is on the lottie side
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/animation/content/MergePathsContent.java#L53

**Comment by gpeal** [comment]
@dnfield I think in this case, it may be that they are using a puppet or fill effect, neither of which are supported by Lottie. It would be hard to debug this without the original animation though so I'm going to close this issue for now. Merge paths are also inadvisable because they are only supported on KitKat and above.

Neat that you're working on a Flutter port though! I've never used it but have been curious. How has it been?

**Comment by dnfield** [comment]
The thing is it breaks if you enable merge paths but doesn't if you turn them off.  I have the same behavior in my flutter port and I'm looking for clarification on these mappings.

Flutter's been great.  I nearly have parity with the Android version and I'm hoping to release an initial version soon (need a PR I have open in the engine to land that enables path measure and path operations).

**Comment by dnfield** [comment]
There's definitely some issue with effects on it as well though.
