### ISSUE TITLE
Progress set by setMinProgress() is ignored when playing animation

### ISSUE THREAD

**Issue by borwoj** [airbnb/lottie-android#739]
Lottie 2.5.4, Android 8.1, Nexus 5X
```
<com.airbnb.lottie.LottieAnimationView
          android:id="@+id/tick"
          android:layout_width="80dp"
          android:layout_height="80dp"
          app:lottie_autoPlay="false"
          app:lottie_fileName="lottie/tick.json"
          />
```
```
tick.setMinProgress(0.5f)
tick.playAnimation()
```
Javadoc:
> Sets the minimum progress that the animation will start from when playing or looping.

Expected result:
Animation starts from progress 0.5.

Actual result:
Animation starts from the beginning.

[tick.zip](https://github.com/airbnb/lottie-android/files/1947322/tick.zip)

**Comment by borwoj** [comment]
Seems to work fine on 2.5.0.

**Comment by PaulWoitaschek** [comment]
It's because of https://github.com/airbnb/lottie-android/pull/717

setMinProgress is calling:
 ```
setMinFrame((int) MiscUtils.lerp(minProgress, composition.getStartFrame(), composition.getEndFrame()));`
```

Whereas lerp is defined as 
```java
public static float lerp(float a, float b, @FloatRange(from = 0f, to = 1f) float percentage) {
    return a + percentage * (b - a);
}
```

Which does not make any sense.
If startFrame is 0 and endFrame is 100 and minProgress is `0.2F` then that would evaulate to:
`lerp(0.2F, 0, 100) = 0.2F + 100 * (0 - 0.2)=-19,8`
