### ISSUE TITLE
Cache not working concurrent

### ISSUE THREAD

**Issue by PaulWoitaschek** [airbnb/lottie-android#741]
I use Lottie to show about 15x the same animation in a recyclerview. Because setAnimation does not check for pending requests, creating 15 views with the same animation leads to the animation be parsed 15 times and then be put 15 times into the cache.

Instead Lottie should check  if there are pending requests and join them instead of creating new ones.

**Comment by gpeal** [comment]
@PaulWoitaschek I've avoided doing this because it adds significant code complexity and maintainability of the code. If possible, for you use case, can you create the LottieComposition yourself ([docs](http://airbnb.io/lottie/android/android.html#using-lottiecomposition-to-preload-an-animation)). That would solve your problem.
