### ISSUE TITLE
[request] Combining animations

### ISSUE THREAD

**Issue by dmallcott** [airbnb/lottie-android#745]
Hey good people, hope you're all well. 

Recently I could've used some support for combining different animations and playing them as a whole. Something along the lines of combining the jsons programmatically and then using the result as the actual animation. Is this possible at the moment? If not, is there interest in making this a feature?

**Comment by gpeal** [comment]
@dmallcott You have a few options:
1) Overlay multiple LottieAnimationViews on top of eachother then call play on each of them. You could also wrap then in a parent view so that you call play on the parent ViewGroup and it delegates to each of its children.
2) Use a LayerDrawable with an array of LottieDrawables.

I don't see a reason to add this to the core library though.
