### ISSUE TITLE
Proguard question for lottie

### ISSUE THREAD

**Issue by tianshaokai** [airbnb/lottie-android#786]
Warning: com.airbnb.lottie.utils.BaseLottieAnimator: can't find referenced method 'void onAnimationStart(android.animation.Animator,boolean)' in library class android.animation.Animator$AnimatorListener
Warning: com.airbnb.lottie.utils.BaseLottieAnimator: can't find referenced method 'void onAnimationEnd(android.animation.Animator,boolean)' in library class android.animation.Animator$AnimatorListener

**Comment by tianshaokai** [comment]
It's good to add the following

-dontwarn com.airbnb.lottie.**
-keep class com.airbnb.lottie.** {*;}

**Comment by kanytu** [comment]
That's just a lazy solution. Might as well turn off minify.

**Comment by AaronEvans-BR** [comment]
Any particular reason @kanytu ? I would agree but since lottie is open source anyway.

**Comment by kanytu** [comment]
The reason is just keeping it all. Not obfuscating a single thing.

While I agree with you that Lottie is open source, it does matter because having it obfuscated prevents hackers from identifying the lottie version that the APK is using. And without the version, they don't know which code is being used.

**Comment by mzahar** [comment]
Proguard and obfuscation it's not only about hackers attack. Proguard also makes code smaller (that mean smaller apk size) and improve performance of application.
