### ISSUE TITLE
Adding subviews at runtime

### ISSUE THREAD

**Issue by jlimzynga** [airbnb/lottie-android#795]
My iOS counterpart has been able to implement the desired effect following the example detailed here: http://airbnb.io/lottie/ios/addsubviews.html

I see no capability to do that in Android - is this something that's available but not yet documented? We're on version 2.5.5.

**Comment by gpeal** [comment]
The Android and iOs renderers work differently. Lottie Android uses a Drawable to do its rendering. A drawable can be rendered in a view but not vice versa. You may have to do some manual work to accomplish the same thing.

**Comment by ionull** [comment]
Any idea how to combine another drawable to some element in LottieAnimationview? I read the document, and for now, only basic properties can be changed like color, opacity etc.

**Comment by gpeal** [comment]
@ionull You could use an image with `ImageAssetDelegate` then render your drawable to a bitmap if it is static.

**Comment by ionull** [comment]
@gpeal it's a moving element :(

**Comment by angelolloqui** [comment]
Any plan to support this in future? why not being able to add custom Layer to the composition? Couldn't my custom Layer just implement the `draw` method and draw directly in the canvas? are there other things I am missing?

Because another option (not that good but workable) would be to add listeners to get the exact position of a layer during the animation. That way I could at least place my view exactly there, including transformed size, and adding manually opacities and alike would make the trick (except for the depth, which in my case at least is not an issue)

**Comment by gpeal** [comment]
@angelolloqui Can you open a new issue with a proposal for the exact API you would want. We can start a discussion there. It seems like something we could reasonably add.

**Comment by gpeal** [comment]
The problem with Views themself is that they can't be a child of a Drawable
