### ISSUE TITLE
Bug: in docs, it says the SDK can "Download animations from the network"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#869]
This:

http://airbnb.io/lottie/android/avd.html

![image](https://user-images.githubusercontent.com/5357526/43703540-b22a49fa-9965-11e8-9b2e-09a613de9558.png)

This is incorrect, as is shown here:
https://github.com/airbnb/lottie-android/issues/338

You can't set a url just in a single line. Some work need to be done first.

**Comment by gpeal** [comment]
@AndroidDeveloperLB As of the latest release, you can do it by passing in the json string from the response. We do it all the time. In fact, the Lottie sample app does it.

Coincidentally, I have been working on this though:
https://github.com/airbnb/lottie-android/pull/868

**Comment by AndroidDeveloperLB** [comment]
Passing the json string from the response doesn't make the library "download animations from the network". The response you write about is after I already got the access from the network. The network access is something that's not a part of the library.
Currently, the description brings a false claim, that this library can download the animation. It can't.

**Comment by gpeal** [comment]
@AndroidDeveloperLB is this how you normally communicate with your coworkers? 

I work on Lottie on nights and weekends because I enjoy enabling new things for other people. I don't get paid for Lottie and 99% of the work I do on it isn't for things that Airbnb needs.

Working on Lottie has been one of the most rewarding experiences of my career and I have gotten to meet some amazing people as a result. In general, if you want people to do things for you, should have more respect for them and their time.

**Comment by AndroidDeveloperLB** [comment]
Where exactly have I shown disrespect?
I state a clear explanation:
This is a bug. It's not supposed to be written there.

**Comment by AndroidDeveloperLB** [comment]
And why close it? It's still in the description there.
Is it now available to use it using a URL alone? Does it now download the animation?
